# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LinaWolf\FormDoubleOptIn\:
    resource: '../Classes/*'

  LinaWolf\FormDoubleOptIn\Upgrades\FormDoubleOptInNamespaceMigrationUpgradeWizard:
    tags:
      - name: install.upgradewizard

  LinaWolf\FormDoubleOptIn\EventListener\RedirectToConfirmationFormEventListener:
    tags:
      - name: event.listener
        identifier: 'redirect-to-confirmation-form'
        event: LinaWolf\FormDoubleOptIn\Event\RedirectToConfirmationFormEvent
